const binary=["01001001 01010100 01001110 01000101 01010100","10101010 00110101 11001010 01010101 01100110","01010011 01111001 01110011 01110100 01100101","11001100 10101010 01001101 00110011 11100010"];
const nodes=[[10,18],[28,32],[48,17],[69,31],[87,16],[18,67],[42,77],[64,62],[83,76]];
export default function Home(){return <main>
<div className="tech-bg" aria-hidden="true"><div className="grid-glow"/><div className="binary-layer">{binary.map((x,i)=><span key={i} className={`binary-line b${i}`}>{x}</span>)}</div><svg className="network-layer" viewBox="0 0 100 100" preserveAspectRatio="none"><g>{[[0,1],[1,2],[2,3],[3,4],[1,5],[5,6],[6,7],[7,8],[3,7],[4,8]].map(([a,b],i)=><line key={i} x1={nodes[a][0]} y1={nodes[a][1]} x2={nodes[b][0]} y2={nodes[b][1]}/>)}</g>{nodes.map((n,i)=><circle key={i} cx={n[0]} cy={n[1]} r=".75"/>)}</svg><span className="code-symbol s1">&lt;/&gt;</span><span className="code-symbol s2">{'{}'}</span><span className="code-symbol s3">01</span><span className="code-symbol s4">#</span></div>
<header className="navbar"><a className="brand" href="#home">Jidjeyd<span>.</span></a><nav><a href="#home">Home</a><a href="#education">Education</a><a href="#projects">Projects</a><a href="#contact">Contact</a></nav></header>
<section id="home" className="section hero"><div className="hero-content"><div className="hero-copy"><h1>Marian Jade Gorenzo</h1><p className="username">@Jidjeyd</p><p className="bio">Turning coffee into code and bugs into features.</p></div><div className="portrait-wrap"><div className="portrait-glow"/><div className="portrait-frame"><img src="/profile.png" alt="Marian Jade Gorenzo"/><div className="scanline"/></div><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/></div></div><div className="scroll-note">scroll_down <span>↓</span></div></section>
<section id="education" className="section content-section"><div className="section-heading"><span>01</span><h2>Education</h2></div><div className="glass-card education-card"><div className="card-icon">&lt;/&gt;</div><div><p className="label">College</p><h3>3rd Year BSIT</h3><p className="major">Major in Network Design and Management</p><p className="muted">Nueva Vizcaya State University (NVSU)</p></div><div className="status">STUDENT</div></div></section>
<section id="projects" className="section content-section"><div className="section-heading"><span>02</span><h2>Projects</h2></div><div className="glass-card empty-card"><div className="empty-code">{'{ }'}</div><h3>No projects added yet.</h3><p className="muted">Projects will appear here as they are built.</p></div></section>
<section id="contact" className="section content-section"><div className="section-heading"><span>03</span><h2>Contact</h2></div><div className="contact-grid"><a className="glass-card contact-card" href="mailto:marianjade3127@gmail.com"><span className="contact-icon">@</span><div><p className="label">Email</p><h3>marianjade3127@gmail.com</h3></div><span className="arrow">↗</span></a><a className="glass-card contact-card" href="https://github.com/marianjade" target="_blank" rel="noreferrer"><span className="contact-icon">&lt;/&gt;</span><div><p className="label">GitHub</p><h3>github.com/marianjade</h3></div><span className="arrow">↗</span></a></div></section>
<footer><div className="footer-line"/><p>© 2026 Programmer Profile. All rights reserved.</p><span>Jidjeyd // IT</span></footer></main>}
